name: Build and Deploy

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zeig mal
        run: |
          ls

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
