name: Build and Deploy

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Lass mal schauen
        run: |
          echo "Hello! It's me"
          ls

      - name: Checkout
        uses: actions/checkout@v4

      - name: Zeig noch mal
        run: |
          ls
