name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm clean-install

      - name: NPM build
        run: npm run build

      - name: Show dist folder recursive
        run: ls -R dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: dist

      - name: Show credentials
        run: |
          echo "${{ vars.BUCKET_NAME }}"
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
